export default Object.freeze({
  GLOBAL_TEXT_SETTINGS: "textSettingsGlobal",
  TEXT_SETTINGS: "textSettings",
  EMPTY: "empty",
  NAME: "name",
  IMAGES: "images",
  TEXTS: "texts",
  THUMB: "thumb",
  POSITION: "position",
  KEY: "key",
  VALUE: "value",
  ORIGINAL_NAME: "originalName",
  UNSAVED: "unsaved",
  BOLD: "bold",
  ITALIC: "italic",
  OUTLINE: "outline",
  TOP: "top",
  TEXT_COLOR: "textColor",
  BACKGROUND_COLOR: "backgroundColor",
  SETTINGS: "settings",
  LIGHTS_OFF: "lightsOff",
  PREMIUM: "premium",

  // bold: false,
  //     italic: true,
  //     outline: false,
  //     top: false,
  //     textColor: "#fff",
  //     backgroundColor: "#F39C12",
});
